package com.randomnoun.dmx.web.action;

import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;

import com.randomnoun.dmx.web.struts.ActionBase;
import com.randomnoun.dmx.web.struts.DmxHttpRequest;

/**
 * Forwards to a JSP
 *
 * <p>HTTP Parameters used in this action:
 * <br><i>(none)</i>
 *
 * <p>Request/Session Attributes used in this action:
 * <br><i>(none)</i>
 *
 * <p>Forwards generated by this action:
 * <attributes>
 * success - this action will always return the 'success' forward
 * </attributes>
 *
 * @version         $Id$
 * @author          knoxg
 */
public class DisplayAction
    extends ActionBase
{
    
    
    
    /** Return a logger instance for this class */
    public Logger logger = Logger.getLogger(DisplayAction.class);

    /**
     * Perform this struts action. See the javadoc for this
     * class for more details.
     *
     * @param mapping The struts ActionMapping that triggered this Action
     * @param form An ActionForm (if available) holding user input for this Action
     * @param request The HttpServletRequest for this action
     * @param response The HttpServletResponse for this action
     *
     * @return An ActionForward representing the result to return to the end-user
     *
     * @throws Exception If an exception occurred during action processing
     */
    public String execute(DmxHttpRequest request, HttpServletResponse response)       
        throws Exception
    {
        return "success";
    }
}
