CREATE TABLE `fixtureDef` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `fixtureDefClassName` VARCHAR(100) NOT NULL,
  `fixtureDefScript` MEDIUMTEXT NOT NULL,
  `fixtureControllerClassName` VARCHAR(100) NOT NULL,
  `fixtureControllerScript` MEDIUMTEXT NOT NULL,
  `channelMuxerClassName` VARCHAR(100) DEFAULT NULL,
  `channelMuxerScript` MEDIUMTEXT DEFAULT NULL,
  `dmxChannels` INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY (`Id`)
)
ENGINE = InnoDB;


CREATE TABLE `fixture` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `fixtureDefId` INTEGER UNSIGNED NOT NULL,
  `name` VARCHAR(100),
  `dmxOffset` INTEGER UNSIGNED NOT NULL,
   `x` FLOAT DEFAULT NULL,
   `y` FLOAT DEFAULT NULL,
   `z` FLOAT DEFAULT NULL,
   `lookingAtX` FLOAT DEFAULT NULL,
   `lookingAtY` FLOAT DEFAULT NULL,
   `lookingAtZ` FLOAT DEFAULT NULL,
   `upX` FLOAT DEFAULT NULL,
   `upY` FLOAT DEFAULT NULL,
   `upZ` FLOAT DEFAULT NULL,
  PRIMARY KEY (`Id`)
)
ENGINE = InnoDB;

CREATE TABLE `showDef` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `className` VARCHAR(100) NOT NULL,
  `script` MEDIUMTEXT NOT NULL,
  `javadoc` MEDIUMTEXT DEFAULT NULL,
  PRIMARY KEY (`Id`)
)
ENGINE = InnoDB;

CREATE TABLE `show` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `showDefId` INTEGER UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `onCancelShowId` INTEGER UNSIGNED,
  `onCompleteShowId` INTEGER UNSIGNED,
  `showGroupId` INTEGER UNSIGNED DEFAULT NULL, 
  PRIMARY KEY (`Id`)
)
ENGINE = InnoDB;


CREATE TABLE `showProperty` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `showId` INTEGER UNSIGNED NOT NULL,
  `key` VARCHAR(100) NOT NULL,
  `value` VARCHAR(255),
  PRIMARY KEY (`Id`)
)
ENGINE = InnoDB;

CREATE TABLE `fixtureDefImage` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `fixtureDefId` INTEGER UNSIGNED NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `size` INTEGER UNSIGNED NOT NULL,
  `contentType` VARCHAR(200) NOT NULL,
  `fileLocation` VARCHAR(200) NOT NULL COMMENT 'relative to app base specified in appConfig',
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;



