CREATE TABLE `comedy_dev`.`fixtureDef` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `className` VARCHAR(100) NOT NULL,
  `script` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`Id`)
)
ENGINE = InnoDB;


CREATE TABLE `comedy_dev`.`fixture` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `fixtureDefId` INTEGER UNSIGNED NOT NULL,
  `name` VARCHAR(100),
  `dmxOffset` INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY (`Id`)
)
ENGINE = InnoDB;

CREATE TABLE `comedy_dev`.`showType` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `className` VARCHAR(100) NOT NULL,
  `script` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`Id`)
)
ENGINE = InnoDB;

CREATE TABLE `comedy_dev`.`show` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `showTypeId` INTEGER UNSIGNED NOT NULL,
  `onCancelShowId` INTEGER UNSIGNED,
  `onCompleteShowId` INTEGER UNSIGNED,
  PRIMARY KEY (`Id`)
)
ENGINE = InnoDB;

CREATE TABLE `comedy_dev`.`showProperty` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `showId` INTEGER UNSIGNED NOT NULL,
  `key` VARCHAR(100) NOT NULL,
  `value` VARCHAR(255),
  PRIMARY KEY (`Id`)
)
ENGINE = InnoDB;





